server:
  port: 8081


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.2.15:8080/auth/realms/rya

debug: true
logging:
  level:
    root: DEBUG
