server:
  port: 8081

database:
  implementation: accumulo

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.localhost/auth/realms/rya
          jwk-set-uri: http://keycloak.localhost/auth/realms/rya/protocol/openid-connect/certs

debug: true
logging:
  level:
    "org.apache.rya.web2.controllers": DEBUG
rya:
  sparql:
    api:
      clientId: sparql-api
      authorizationsClaim: keywords
  instance:
    name: rya
    username: root
    password: secret
    zk: localhost:2181
    tableprefix: rya
    displayqueryplan: false
